[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.pylsp]
command = "pylsp"

[[language]]
name = "python"
scope = "source.python"
injection-regex = "py(thon)?"
file-types = ["py", "pyi", "py3", "pyw", "ptl", "rpy", "cpy", "ipy", "pyt", { glob = ".python_history" }, { glob = ".pythonstartup" }, { glob = ".pythonrc" }, { glob = "SConstruct" }, { glob = "SConscript" }]
shebangs = ["python"]
roots = ["pyproject.toml", "setup.py", "poetry.lock", "pyrightconfig.json"]
comment-token = "#"
indent = { tab-width = 4, unit = "    " }
language-servers = ["ruff", "pylsp"]
auto-format = true
formatter = { command = "ruff" , args = ["format", "-"] }
